api:
  items:
    url: ${API_ITEMS_URL}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/coupons
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:Admin2022$}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
