api:
  items:
    url: ${API_ITEMS_URL}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:coupons}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
